### PR TITLE
Add CTM Glow to Refined Storage Transformer

### PR DESCRIPTION
**Pull request by VT-14**
I have confirmed that this works as a texture pack with CTM both included and excluded.  However, I'm having issues getting gradle to compile the mod and have been unable to confirm that this works as part of the mod itself.

### CODE REVIEW

**Comment by SanAndreasP** [comment]
How did you set it up?
You'd need to do gradlew setupDecompWorkspace``` or ```gradlew setupDevWorkspace``` so it downloads the dependencies

**Comment by VT-14** [comment]
Well, that was exactly what I was messing up.  Thank you.  

I have now confirmed that it is working as expected from the current version on my fork.

**Comment by SanAndreasP** [comment]
nice, I'll merge it and it will be included in the next update

**Comment by SanAndreasP** [comment]
Oh, btw, you saw the wire_colors.json for recoloring the wires? Did you get around to testing it?

**Comment by VT-14** [comment]
Not yet, but it looks like it should work.  Thank you.

Texture packs will probably wait until Tuesday or Wednesday (EST).  Happy Holidays.

**Comment by VT-14** [comment]
I decided to test it.  Yes, it is working.  Thanks!

**Comment by SanAndreasP** [comment]
Nice, now I can sleep well knowing that, heh.

**Pull request merged**
